### ISSUE TITLE
Small Memory Leak

### ISSUE THREAD

**Issue by Trott** [dergachev/solr-security-proxy#8]
The listener for `proxyError` is being added over and over with each request. As a result, if you have more than ten requests, you get a warning like this:

````
(node) warning: possible EventEmitter memory leak detected. 11 proxyError listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:236:17)
    at /Users/node/solr-security-proxy/node_modules/http-proxy/lib/node-http-proxy/routing-proxy.js:63:27
    at Array.forEach (native)
    at null.<anonymous> (/Users/node/solr-security-proxy/node_modules/http-proxy/lib/node-http-proxy/routing-proxy.js:62:33)
    at emitTwo (events.js:87:13)
    at emit (events.js:169:7)
    at options.Emitter.emit (/Users/node/solr-security-proxy/node_modules/vows/lib/vows.js:237:24)
    at addListener (events.js:204:12)
    at Array.<anonymous> (/Users/node/solr-security-proxy/solr-security-proxy.js:69:13)
    at Server.handler (/Users/node/solr-security-proxy/node_modules/http-proxy/lib/node-http-proxy.js:175:40)
````

**Comment by dergachev** [comment]
I believe this was closed by  #11
